### ISSUE TITLE
Gives vastly diff (and worse mimimization by factor of 2)

### ISSUE THREAD

**Issue by duggar** [eco-hydro/curvefit.jl#3]
Gives very diff minimum objective value when compared to nlminb in R and BFGS of scipy.

The mimima found differs by a factor of 2, for mimizing SSE fitting a power law equation to data

**Comment by kongdd** [comment]
please give your example

**Comment by duggar** [comment]
A 3-Stage optimization of LPPLS power-law type of curve:

`using MarketData, nlminb, DataFrames, TimeSeries

function LPPLS(n::Int64,params::Vector{Float64})
    beta,ω,A,B,C1,C2,tc = params
    sd = fill(1.0,n)
    tt = collect(1.0:1.0:n)
    ft = (tc .- tt) .^beta
    gt = ((tc .- tt) .^beta) .* cos.(ω*log.(tc.-tt))
    ht = ((tc .- tt) .^beta) .* sin.(ω*log.(tc.-tt))
    fit = (A*sd .+ beta*ft .+ C1*gt .+ C2*ht)
    return fit
end

function LPPLS_resid(params,ds)
    n = length(ds)
    fits = LPPLS(n,params)
    res = ds .- fits    
    return res
end 

function LPPLS_obj(ds, pow, params)
    res = LPPLS_resid(params,ds)
    obj = sum(abs.(res).^pow)
    return obj
end

function LPPLS_Step_1(params,ds)
    n = length(ds)
    tc = n+0.1*n
    ret = LPPLS_obj(ds,2.0,[params;tc])
    return ret
end

function LPPLS_Step_2(params, prev_params, ds)
    tc = params[1]
    beta,ω,A,B,C1,C2 = prev_params
    new_params = [beta,ω,A,B,C1,C2,tc]
    ret = LPPLS_obj(ds,2.0,new_params)
end

function LPPLS_Step_3(params, ds)
    ret = LPPLS_obj(ds, 2.0, params)
    return ret
end






data = yahoo("ETH-USD");
data = DataFrame(data)
dropmissing!(data)
ts = TimeArray(data; timestamp = :timestamp)
ts = from(ts,Date(2020,3,27))
y = values(ts[:AdjClose])

y = log.(y)

x0 = [0.5,6.0,y[end],-0.02,0.0,0.0]

lamda = x -> LPPLS_Step_1(x,y)
op1 = optim_nlminb(x0,lamda)
x1=[length(y)*1.1]
op2 = optim_nlminb(x1, x -> LPPLS_Step_2(x,op1["par"],y))
xf = [op1["par"];op2["par"]]
op3 = optim_nlminb(xf, x -> LPPLS_Step_3(x,y))

params = op3["par"]
res = LPPLS_resid(params,y)
β,ω,A,B,C1,C2,tc = params
@show β,ω,A,B,C1,C2,tc

`

**Comment by duggar** [comment]
Same in R:

`library(quantmod)
library(doParallel)
library(parallel)
library(zoo)
library(factoextra)
library(cluster)
library(tseries)
library(dplyr)



lppl_estimate_1s=function(x, par_start = c(bet=0.5, ome=6, A=x[NROW(x)], B=0, C1=0, C2=0), max.win.tc=0.1){
  
  # Compose function to be MINIMIZED:
  LPPL_LLH1 = function(parm){
    bet = parm[1]; ome = parm[2]; A = parm[3]; B = parm[4]; C1=parm[5]; C2=parm[6];
    n=NROW(x)       # number of observations
    sdum=rep(1,n)
    tt_sim=seq(1, n, 1)
    tc=NROW(x)+max.win.tc*NROW(x)
    f_t=(tc - tt_sim)^bet;
    g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
    h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
    Y = x
    et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
    et=zoo::coredata(et)
    ll=sum(et*et)
  }
  
  # Estimate Parameters:
  fit = nlminb(par_start, objective=LPPL_LLH1, control = list(trace=0), hessian=TRUE)
  
  par_est1=c( (fit$par) )
  return(par_est1)
}

lppl_estimate_2s=function(x,par, max.win.tc=0.1){
  
  #  Create the starting value for the critical time tc:
  par_start = c(tc=NROW(x)+max.win.tc*NROW(x))
  
  #  Compose function to be MINIMIZED:
  LPPL_LLH2 = function(parm){
    tc=parm[1]
    bet = par[1]; ome = par[2]; A = par[3]; B = par[4]; C1=par[5]; C2=par[6];
    n=NROW(x)       # number of observations
    sdum=rep(1,n)
    tt_sim=seq(1, n, 1)
    f_t=(tc - tt_sim)^bet
    g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
    h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
    Y = x
    et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
    et=zoo::coredata(et)
    ll=sum(et*et)
  }
  
  #Estimate Parameters:
  fit = nlminb(par_start, objective=LPPL_LLH2, control = list(trace=0), hessian=TRUE)
  par_est2=c( (fit$par) )
  return(par_est2)
}

lppl_estimate_3s=function(x,par1,par2){
  
  # Create the starting values for the parameter vector:
  par_start = c(par1,par2)
  
  # Compose function to be MINIMIZED:
  LPPL_LLH3 = function(parm){
    bet = parm[1]; ome = parm[2]; A = parm[3]; B = parm[4]; C1=parm[5]; C2=parm[6]; tc =parm[7];
    n=NROW(x)      # number of observations
    sdum=rep(1,n)
    tt_sim=seq(1, n, 1)
    f_t=(tc - tt_sim)^bet
    g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
    h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
    Y = x
    et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
    et=zoo::coredata(et)
    ll=sum(et*et)
  }
  
  # Estimate Parameters:
  fit = nlminb(par_start, objective=LPPL_LLH3, control = list(trace=0), hessian=TRUE)
  
  #Computation of residuals and KPSS test statistic
  bet = fit$par[1]; ome = fit$par[2]; A = fit$par[3]; B = fit$par[4]; C1=fit$par[5]; C2=fit$par[6]; tc =fit$par[7];
  n=NROW(x)
  sdum=rep(1,n)
  tt_sim=seq(1, n, 1)
  f_t=(tc - tt_sim)^bet
  g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
  h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
  Y = x
  et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
  kpsst=tseries::kpss.test(et)
  
  par_est=c( (fit$par), kpsst$statistic )
  return(par_est)
}

lppl_estimate=function(x, par_start = c(bet=0.5, ome=6, A=x[NROW(x)], B=0, C1=0, C2=0), max.win.tc=0.1){
  bb1=lppl_estimate_1s(x, par_start, max.win.tc)
  bb2=lppl_estimate_2s(x,bb1, max.win.tc)
  bb3=lppl_estimate_3s(x,bb1,bb2)
  C.param=bb3[5]/cos(atan(bb3[6]/bb3[5]))
  crash.rate=-bb3[4]*bb3[1]-abs(C.param)*sqrt(bb3[1]^2+bb3[2]^2)
  names(crash.rate)<-"crash.rate"
  param.JLS=c(bb3[1:2],acos(bb3[5]/C.param), bb3[3:4],C.param, bb3[7])
  names(param.JLS)<-c("bet","ome","phi","A","B","C", "tc")
  param.FS=c(bb3[1:7])
  names(param.FS)<-c("bet","ome","A","B","C1","C2","tc")
  
  bet = bb3[1]; ome = bb3[2]; A = bb3[3]; B = bb3[4]; C1=bb3[5]; C2=bb3[6]; tc =bb3[7];
  n=NROW(x)
  sdum=rep(1,n)
  tt_sim=seq(1, n, 1)
  f_t=(tc - tt_sim)^bet
  g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
  h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
  Y=x
  et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
  Yfit = sdum*A + B*f_t + C1*g_t + C2*h_t
  relative.error=abs(mean( (Y-Yfit)/Yfit ))
  
  results <-list(param.JLS=param.JLS, param.FS=param.FS, KPSS.res=bb3[8], crash.rate=crash.rate, relative.error=relative.error, resids=et)
  return(results)
}


fromt <- "2020-03-27"
tot = "2021-12-19"
ss = paste0(s,".NS")
ticker = getSymbols(ss,from = fromt, to=tot,auto.assign = F )
date_txt_from = "2020-03-27"
date_txt_to_base = "2021-12-28"
ticker=na.omit(ticker)
cols = c('Open', 'High', 'Low','Close',"Volume",'AdjClose')
colnames(ticker) = cols
dates = index(ticker)
ticker = as.data.frame(ticker,row.names = NULL)
ticker$Date <- dates
ticker = ticker[c("Date","AdjClose")]
ticker$Date <- as.Date(ticker$Date, format = "%Y-%m-%d")
ticker$logP = log(ticker$AdjClose)
aa =base::log(zoo::coredata(rticker$AdjClose))}
est.all<-lppl_estimate(aa, max.win.tc=0.1)
  
  to_base <- as.Date(date_txt_to_base)
  #date_txt_from <- as.character(to_base-860)
  from_base <- as.Date(date_txt_from)
  
  df_df<-NULL
  nbre_step_backward=700
  cl <- parallel::makeCluster(detectCores()-1)
  doParallel::registerDoParallel(cl)
  type_p = "log"
  df_df <- foreach (i = seq(0,nbre_step_backward,1), .combine = rbind) %dopar% {
    from <- from_base+i
    rticker = base::subset(ticker, ticker$Date >= from & ticker$Date <= to_base)
    if (nrow(rticker)>20) {
      if (type_p=="log")
      {aa =base::log(zoo::coredata(rticker$AdjClose))}
      else
      {aa =zoo::coredata(rticker$AdjClose)}
      
      est.all<-lppl_estimate(aa, max.win.tc=0.1)
      plpp = est.all$param.JLS
      m = plpp[1]
      omega = plpp[2]
      phi = plpp[3]
      A = plpp[4]
      B = plpp[5]
      C = plpp[6]
      tc = plpp[7]
      crash = est.all$crash.rate
      kpss.res = est.all$KPSS.res
      rel.err = est.all$relative.error
      osc = omega/(2*pi)*log(abs((tc-1)/(tc-length(aa))))
      damp =(m/omega)*abs(B/C)
      du=  round(tc-length(aa),2)
      df_df <- c(date_txt_from, date_txt_to_base, format(from,"%Y-%m-%d"), tc,length(aa),du,m,omega,phi,A,B,C,crash,kpss.res, rel.err,osc,damp)
    }
  }
  
  cnames <- c("from","to","from_step","tc","td","days_until","m","omega","phi","A","B","C","crash","kpss","relerr","osc","damp")
  colnames(df_df) = cnames
  df_df = as.data.frame(df_df)
  i <- 4:17
  df_df[i] <- lapply(df_df[i],as.numeric)
  conf.A = df_df %>% filter(m >= 0.01 & m<1.0 & omega>2 & omega<25 & osc>2.5 & damp>0.8 & tc < 1.1*td &  B<0 & relerr<0.05  )
  conf.B = df_df %>% filter(m > 0.0 & m<1 & crash>0  & kpss<0.463 & B<0 & tc < 1.1*td)
  
  
  
  mode_confa = round(mean(conf.A$days_until),2)
  med_confa = round(median(conf.A$days_until),2)
  mode_confb = round(mean(conf.B$days_until),2)
  med_confb = round(median(conf.B$days_until),2)
  print(paste0("The  Mode and Median for Conf A is ", mode_confa, " and ", med_confa, " the confidence in this is ", nrow(conf.A)/nrow(df_df)))
  print(paste0("The Mode and Median for Conf B is ", mode_confb, " and ", med_confb, " the confidence in this is ", nrow(conf.B)/nrow(df_df)))
  ca = clustered(conf.A)
  ca = round(ca,2)
  print(ca[4])
  ciA = round(nrow(conf.A)/nrow(df_df)*100,2)
  print(paste0("Conf A - Mean :",ca[1]," - Median :", ca[2], " Std :", ca[3], " CI :",ciA ))
  cb = clustered(conf.B)
  print(cb[4])
  cb = round(cb,2)
  ciB = round(nrow(conf.B)/nrow(df_df)*100,2)
  print(paste0("Conf B - Mean :",cb[1]," - Median :", cb[2], " Std :", cb[3],  " CI :", ciB))
  if (type_p=="log")
  { A_sp = round(exp(median(conf.A$A)),2)
  B_sp = round(exp(median(conf.B$A)),2)}else{
    A_sp = round(median(conf.A$A),2)
    B_sp =round(median(conf.B$A),2)}
  out = rbind(out,c(s,ticker$Date[nrow(ticker)],ticker$AdjClose[nrow(ticker)],ciA,ca[1],ca[2],ca[3],mode_confa,med_confa,A_sp,ciB,cb[1],cb[2],cb[3],mode_confb,med_confb, B_sp))
}
parallel::stopCluster(cl)
colnames(out)<-c('symbol','date','curr_price','confA','A_mean','A_median','A_std','A_full_mean','A_full_med','A_sp','confB', 'B_mean','B_median','B_std','B_full_mean','B_full_med','B_sp')
fname = paste0(format(ticker$Date[nrow(ticker)], "%Y%m%d"),"_",type_p,"_","R")
write.csv(out,fname)`

**Comment by duggar** [comment]
Same in R ----



`library(quantmod)
library(doParallel)
library(parallel)
library(zoo)
library(factoextra)
library(cluster)
library(tseries)
library(dplyr)



lppl_estimate_1s=function(x, par_start = c(bet=0.5, ome=6, A=x[NROW(x)], B=0, C1=0, C2=0), max.win.tc=0.1){
  
  # Compose function to be MINIMIZED:
  LPPL_LLH1 = function(parm){
    bet = parm[1]; ome = parm[2]; A = parm[3]; B = parm[4]; C1=parm[5]; C2=parm[6];
    n=NROW(x)       # number of observations
    sdum=rep(1,n)
    tt_sim=seq(1, n, 1)
    tc=NROW(x)+max.win.tc*NROW(x)
    f_t=(tc - tt_sim)^bet;
    g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
    h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
    Y = x
    et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
    et=zoo::coredata(et)
    ll=sum(et*et)
  }
  
  # Estimate Parameters:
  fit = nlminb(par_start, objective=LPPL_LLH1, control = list(trace=0), hessian=TRUE)
  
  par_est1=c( (fit$par) )
  return(par_est1)
}

lppl_estimate_2s=function(x,par, max.win.tc=0.1){
  
  #  Create the starting value for the critical time tc:
  par_start = c(tc=NROW(x)+max.win.tc*NROW(x))
  
  #  Compose function to be MINIMIZED:
  LPPL_LLH2 = function(parm){
    tc=parm[1]
    bet = par[1]; ome = par[2]; A = par[3]; B = par[4]; C1=par[5]; C2=par[6];
    n=NROW(x)       # number of observations
    sdum=rep(1,n)
    tt_sim=seq(1, n, 1)
    f_t=(tc - tt_sim)^bet
    g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
    h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
    Y = x
    et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
    et=zoo::coredata(et)
    ll=sum(et*et)
  }
  
  #Estimate Parameters:
  fit = nlminb(par_start, objective=LPPL_LLH2, control = list(trace=0), hessian=TRUE)
  par_est2=c( (fit$par) )
  return(par_est2)
}

lppl_estimate_3s=function(x,par1,par2){
  
  # Create the starting values for the parameter vector:
  par_start = c(par1,par2)
  
  # Compose function to be MINIMIZED:
  LPPL_LLH3 = function(parm){
    bet = parm[1]; ome = parm[2]; A = parm[3]; B = parm[4]; C1=parm[5]; C2=parm[6]; tc =parm[7];
    n=NROW(x)      # number of observations
    sdum=rep(1,n)
    tt_sim=seq(1, n, 1)
    f_t=(tc - tt_sim)^bet
    g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
    h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
    Y = x
    et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
    et=zoo::coredata(et)
    ll=sum(et*et)
  }
  
  # Estimate Parameters:
  fit = nlminb(par_start, objective=LPPL_LLH3, control = list(trace=0), hessian=TRUE)
  
  #Computation of residuals and KPSS test statistic
  bet = fit$par[1]; ome = fit$par[2]; A = fit$par[3]; B = fit$par[4]; C1=fit$par[5]; C2=fit$par[6]; tc =fit$par[7];
  n=NROW(x)
  sdum=rep(1,n)
  tt_sim=seq(1, n, 1)
  f_t=(tc - tt_sim)^bet
  g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
  h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
  Y = x
  et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
  kpsst=tseries::kpss.test(et)
  
  par_est=c( (fit$par), kpsst$statistic )
  return(par_est)
}

lppl_estimate=function(x, par_start = c(bet=0.5, ome=6, A=x[NROW(x)], B=0, C1=0, C2=0), max.win.tc=0.1){
  bb1=lppl_estimate_1s(x, par_start, max.win.tc)
  bb2=lppl_estimate_2s(x,bb1, max.win.tc)
  bb3=lppl_estimate_3s(x,bb1,bb2)
  C.param=bb3[5]/cos(atan(bb3[6]/bb3[5]))
  crash.rate=-bb3[4]*bb3[1]-abs(C.param)*sqrt(bb3[1]^2+bb3[2]^2)
  names(crash.rate)<-"crash.rate"
  param.JLS=c(bb3[1:2],acos(bb3[5]/C.param), bb3[3:4],C.param, bb3[7])
  names(param.JLS)<-c("bet","ome","phi","A","B","C", "tc")
  param.FS=c(bb3[1:7])
  names(param.FS)<-c("bet","ome","A","B","C1","C2","tc")
  
  bet = bb3[1]; ome = bb3[2]; A = bb3[3]; B = bb3[4]; C1=bb3[5]; C2=bb3[6]; tc =bb3[7];
  n=NROW(x)
  sdum=rep(1,n)
  tt_sim=seq(1, n, 1)
  f_t=(tc - tt_sim)^bet
  g_t=( (tc - tt_sim)^bet )*cos( ome*log(tc - tt_sim) )
  h_t=( (tc - tt_sim)^bet )*sin( ome*log(tc - tt_sim) )
  Y=x
  et=Y-sdum*A- B*f_t - C1*g_t - C2*h_t
  Yfit = sdum*A + B*f_t + C1*g_t + C2*h_t
  relative.error=abs(mean( (Y-Yfit)/Yfit ))
  
  results <-list(param.JLS=param.JLS, param.FS=param.FS, KPSS.res=bb3[8], crash.rate=crash.rate, relative.error=relative.error, resids=et)
  return(results)
}


fromt <- "2020-03-27"
tot = "2021-12-19"
ss = paste0(s,".NS")
ticker = getSymbols(ss,from = fromt, to=tot,auto.assign = F )
date_txt_from = "2020-03-27"
date_txt_to_base = "2021-12-28"
ticker=na.omit(ticker)
cols = c('Open', 'High', 'Low','Close',"Volume",'AdjClose')
colnames(ticker) = cols
dates = index(ticker)
ticker = as.data.frame(ticker,row.names = NULL)
ticker$Date <- dates
ticker = ticker[c("Date","AdjClose")]
ticker$Date <- as.Date(ticker$Date, format = "%Y-%m-%d")
ticker$logP = log(ticker$AdjClose)
aa =base::log(zoo::coredata(rticker$AdjClose))}
est.all<-lppl_estimate(aa, max.win.tc=0.1)`

**Comment by duggar** [comment]
I goofed up its giving almost similar results, apologies
