### ISSUE TITLE
problem while parallelising

### ISSUE THREAD

**Issue by duggar** [eco-hydro/curvefit.jl#4]
I am using pmap ..

ERROR: LoadError: On worker 2:
ArgumentError: Invalid header in cache file C:\Users\Juuls\.julia\compiled\v1.6\nlminb\jl_5624.tmp.
Stacktrace:
  [1] preferences_hash
    @ .\loading.jl:1478
  [2] compilecache
    @ .\loading.jl:1337
  [3] compilecache
    @ .\loading.jl:1306
  [4] _require
    @ .\loading.jl:1021
  [5] require
    @ .\loading.jl:914
  [6] #1
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\Distributed.jl:79
  [7] #103
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:274
  [8] run_work_thunk
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:63
  [9] run_work_thunk
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:72
 [10] #96
    @ .\task.jl:406

...and 3 more exceptions.

**Comment by kongdd** [comment]
sorry, it is not the bug of `nlminb.jl`
